declare module 'pos' {
  /** Declaration file generated by dts-gen */

  export class Lexer {
    constructor();
    lex(string: string): string[];
  }

  export class Tagger {
    constructor();
    extendLexicon(lexicon: { [key: string]: string[] }): void;
    prettyPrint(taggedWords: string[][]): void;
    tag(words: string[]): string[][];
    wordInLexicon(word: string): boolean;
  }
}
